# radiko局は id、直接配信の局は url を指定します。

[1]
name = K-MIX
id = K-MIX

[2]
name = NHK FM
id = JOAK-FM

[3]
name = J-WAVE
id = FMJ

[4]
name = ニッポン放送
id = LFR

[5]
name = BAYFM78
id = BAYFM78

[6]
name = TOKYO FM
id = FMT

[7]
name = interfm
id = INT

[8]
name = ZIP-FM
id = ZIP-FM

[9]
name = FM802
id = 802

[10]
name = FM COCOLO
id = CCL
